# -*- coding: utf-8 -*-
"""Password_Generator_GC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ye33kzoA5ETNOeE1HvjNv79lmq5XLgnH
"""

from random import sample

symbols ="!@#$%&*()_-+= {}"
lower = "abcdefghijklmnopqrstuvwxyz"
upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
number = "0123456789"
everything = symbols + lower + upper + number


length = input(f"Tell me the lenght of the password you need: ")
number = list(number)
lenl = list(length)
allowed = []

for i in lenl:
  if i not in number:
    print("Only numbers allowed")
    break
  else:
    allowed.append(i)
    if lenl == allowed:
      length= int(''.join(allowed))
      password = "".join(random.sample(everything, length))
      print(f"You requested a password with {length} characters")
      print(f"Your password: {password} \n")